# -*- coding: utf-8 -*-
"""prompt_based_interview_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V1YC9WLg6opJnfooRK-8UrlHVhtwpBDQ
"""

# Prompt-Based Python Interview Question Generator

def generate_questions(prompt):
    prompt = prompt.lower()


    if "loop" in prompt:
        questions = [
            "What is a for loop in Python?",
            "What is the difference between for and while loop?",
            "What does break do in a loop?",
            "What does continue do?"
        ]

    elif "list" in prompt:
        questions = [
            "What is a list in Python?",
            "How is a list different from a tuple?",
            "What is list comprehension?",
            "How do you add elements to a list?"
        ]

    elif "function" in prompt:
        questions = [
            "What is a function?",
            "What is the difference between parameters and arguments?",
            "What is a lambda function?",
            "What is the return statement?"
        ]

    else:
        questions = [
            "What is Python?",
            "What are Python data types?",
            "What is indentation in Python?",
            "Why is Python called an interpreted language?"
        ]

    return questions



user_prompt = input("Enter your prompt: ")
generated_questions = generate_questions(user_prompt)

print("\nGenerated Interview Questions:\n")
for index, question in enumerate(generated_questions, 1):
    print(f"{index}. {question}")

